-- Phase 1: ingestion & triage.
--
-- Three changes:
--   1. organizations gains a public, non-enumerable ingest slug + a key version
--      so a single tenant's ingest key can be revoked without rotating the
--      master secret for everyone.
--   2. incidents gains entity-level dedup identity (fingerprint) and signal
--      rollup counters, plus a PARTIAL unique index that makes find-or-create
--      atomic — 500 simultaneous signals collapse to one incident, count 500,
--      with no application-level lock.
--   3. signals records every triaged signal, escalated OR suppressed. This is
--      the calibration set: without the suppressed rows there is no way to ever
--      measure FPR/TPR and move the threshold off its hand-set prior.

ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "ingest_slug" text;
--> statement-breakpoint
-- Generated by the database, so neither of the two org-creation paths (signup
-- and OAuth first-login) has to remember to set it, and neither can forget.
ALTER TABLE "organizations" ALTER COLUMN "ingest_slug" SET DEFAULT replace(gen_random_uuid()::text, '-', '');
--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "ingest_key_version" integer DEFAULT 1 NOT NULL;
--> statement-breakpoint
-- backfill: every existing org needs a slug before the unique index goes on
UPDATE "organizations" SET "ingest_slug" = replace(gen_random_uuid()::text, '-', '') WHERE "ingest_slug" IS NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "organizations_ingest_slug_idx" ON "organizations" ("ingest_slug");
--> statement-breakpoint

-- ingest-created incidents have no human author
ALTER TABLE "incidents" ALTER COLUMN "user_id" DROP NOT NULL;
--> statement-breakpoint
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "fingerprint" text;
--> statement-breakpoint
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "entity" text;
--> statement-breakpoint
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "signal_count" integer DEFAULT 1 NOT NULL;
--> statement-breakpoint
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "last_seen_at" timestamp with time zone DEFAULT now();
--> statement-breakpoint
-- At most one OPEN incident per (tenant, fingerprint). The predicate is what
-- makes this a dedup key rather than a permanent one: once an incident is
-- resolved it stops occupying the slot and the same entity can open a new one.
-- fingerprint already includes tenant_id, but the index is explicit about it so
-- a future fingerprint change can't silently create cross-tenant collisions.
CREATE UNIQUE INDEX IF NOT EXISTS "incidents_open_fingerprint_idx"
    ON "incidents" ("tenant_id", "fingerprint") WHERE "status" = 'open';
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "signals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"incident_id" uuid,
	"source" text,
	"entity" text,
	"fingerprint" text,
	"severity" text,
	-- calibrated anomaly probability and the threshold it was judged against.
	-- Both are stored: tau moves when the cost ratio changes, and a stored score
	-- with a stored tau lets you replay every past decision under a new tau.
	"score" double precision NOT NULL,
	"threshold" double precision NOT NULL,
	"escalated" boolean NOT NULL,
	"features" jsonb,
	-- bounded excerpt only. Suppressed signals must stay cheap: the whole point
	-- of triage is not paying to store or reason about routine noise.
	"excerpt" text,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "signals_tenant_created_idx" ON "signals" ("tenant_id", "created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "signals_fingerprint_idx" ON "signals" ("tenant_id", "fingerprint");
