/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function homomorphicAdd(ctA: Buffer, ctB: Buffer, serverKey: Buffer): Buffer
export interface EvidenceResult {
  updatedBaseline: Buffer
  anomalyFlag: Buffer
}
export declare function processEvidence(inputCt: Buffer, baselineCt: Buffer, serverKey: Buffer, threshold: number): EvidenceResult
export declare function applyAnomalyThreshold(ct: Buffer, serverKey: Buffer, threshold: number): Buffer
